name: yb_news
description: "YB News production-ready starter with Clean Architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.2.0
  fpdart: ^1.1.1
  flutter_secure_storage: ^10.0.0
  go_router: ^16.2.1
  flutter_screenutil: ^5.9.3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
